export const ADD_OPTION="ADD_OPTION";
export const DELETE_OPTION="DELETE_OPTION";
export const FORM_DATA_CHANGED="FORM_DATA_CHANGED";
export const SUBMIT_FORM_DATA="SUBMIT_FORM_DATA";
export const SUBMIT_FORM_START="SUBMIT_FORM_START";
export const SUBMIT_FORM_END="SUBMIT_FORM_END";
export const SUBMIT_FORM_SUCCESS="SUBMIT_FORM_SUCCESS";